************* Module home.models
models.py:4:0: C0301: Line too long (118/100) (line-too-long)
models.py:8:0: C0301: Line too long (113/100) (line-too-long)
models.py:9:0: C0301: Line too long (130/100) (line-too-long)
models.py:10:0: C0301: Line too long (105/100) (line-too-long)
models.py:66:0: C0301: Line too long (105/100) (line-too-long)
models.py:69:0: C0303: Trailing whitespace (trailing-whitespace)
models.py:79:13: C0303: Trailing whitespace (trailing-whitespace)
models.py:113:0: C0303: Trailing whitespace (trailing-whitespace)
models.py:120:0: C0301: Line too long (106/100) (line-too-long)
models.py:176:0: C0301: Line too long (127/100) (line-too-long)
models.py:177:0: C0301: Line too long (125/100) (line-too-long)
models.py:23:0: E5142: User model imported from django.contrib.auth.models (imported-auth-user)
models.py:26:0: C0411: standard import "uuid" should be placed before third party imports "django.db.models", "django.db.models.Q", "django.contrib.auth.get_user_model", "django.contrib.auth.models.User", "django.shortcuts.reverse", "guardian.shortcuts.assign_perm" (wrong-import-order)

-----------------------------------
Your code has been rated at 7.17/10

